subprojects {
    apply plugin: 'java'

    group = 'org.eagle'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.0'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.0'
        implementation 'com.google.protobuf:protobuf-java:4.33.0'

    }

    test {
        useJUnitPlatform()
    }
}
