// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/src/main/resources/domains.proto
// Protobuf Java Version: 4.31.1

package org.eagle;

@com.google.protobuf.Generated
public final class DomainProto {
  private DomainProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      DomainProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protobuf.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>QOS = 0;</code>
     */
    QOS(0),
    /**
     * <code>QOE = 1;</code>
     */
    QOE(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Type.class.getName());
    }
    /**
     * <code>QOS = 0;</code>
     */
    public static final int QOS_VALUE = 0;
    /**
     * <code>QOE = 1;</code>
     */
    public static final int QOE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return QOS;
        case 1: return QOE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.eagle.DomainProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.Type)
  }

  public interface domainOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.domain)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string domain_name = 1;</code>
     * @return The domainName.
     */
    java.lang.String getDomainName();
    /**
     * <code>string domain_name = 1;</code>
     * @return The bytes for domainName.
     */
    com.google.protobuf.ByteString
        getDomainNameBytes();

    /**
     * <code>.protobuf.Type type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.protobuf.Type type = 2;</code>
     * @return The type.
     */
    org.eagle.DomainProto.Type getType();

    /**
     * <code>int64 interval = 3;</code>
     * @return The interval.
     */
    long getInterval();
  }
  /**
   * Protobuf type {@code protobuf.domain}
   */
  public static final class domain extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.domain)
      domainOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        domain.class.getName());
    }
    // Use domain.newBuilder() to construct.
    private domain(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private domain() {
      domainName_ = "";
      type_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eagle.DomainProto.internal_static_protobuf_domain_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eagle.DomainProto.internal_static_protobuf_domain_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eagle.DomainProto.domain.class, org.eagle.DomainProto.domain.Builder.class);
    }

    public static final int DOMAIN_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object domainName_ = "";
    /**
     * <code>string domain_name = 1;</code>
     * @return The domainName.
     */
    @java.lang.Override
    public java.lang.String getDomainName() {
      java.lang.Object ref = domainName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domainName_ = s;
        return s;
      }
    }
    /**
     * <code>string domain_name = 1;</code>
     * @return The bytes for domainName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDomainNameBytes() {
      java.lang.Object ref = domainName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domainName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_ = 0;
    /**
     * <code>.protobuf.Type type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.protobuf.Type type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public org.eagle.DomainProto.Type getType() {
      org.eagle.DomainProto.Type result = org.eagle.DomainProto.Type.forNumber(type_);
      return result == null ? org.eagle.DomainProto.Type.UNRECOGNIZED : result;
    }

    public static final int INTERVAL_FIELD_NUMBER = 3;
    private long interval_ = 0L;
    /**
     * <code>int64 interval = 3;</code>
     * @return The interval.
     */
    @java.lang.Override
    public long getInterval() {
      return interval_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(domainName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, domainName_);
      }
      if (type_ != org.eagle.DomainProto.Type.QOS.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (interval_ != 0L) {
        output.writeInt64(3, interval_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(domainName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, domainName_);
      }
      if (type_ != org.eagle.DomainProto.Type.QOS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (interval_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, interval_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.eagle.DomainProto.domain)) {
        return super.equals(obj);
      }
      org.eagle.DomainProto.domain other = (org.eagle.DomainProto.domain) obj;

      if (!getDomainName()
          .equals(other.getDomainName())) return false;
      if (type_ != other.type_) return false;
      if (getInterval()
          != other.getInterval()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOMAIN_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDomainName().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInterval());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.eagle.DomainProto.domain parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eagle.DomainProto.domain parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eagle.DomainProto.domain parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eagle.DomainProto.domain parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eagle.DomainProto.domain parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eagle.DomainProto.domain parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eagle.DomainProto.domain parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.eagle.DomainProto.domain parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.eagle.DomainProto.domain parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.eagle.DomainProto.domain parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.eagle.DomainProto.domain parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.eagle.DomainProto.domain parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.eagle.DomainProto.domain prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.domain}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.domain)
        org.eagle.DomainProto.domainOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eagle.DomainProto.internal_static_protobuf_domain_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eagle.DomainProto.internal_static_protobuf_domain_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eagle.DomainProto.domain.class, org.eagle.DomainProto.domain.Builder.class);
      }

      // Construct using org.eagle.DomainProto.domain.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        domainName_ = "";
        type_ = 0;
        interval_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eagle.DomainProto.internal_static_protobuf_domain_descriptor;
      }

      @java.lang.Override
      public org.eagle.DomainProto.domain getDefaultInstanceForType() {
        return org.eagle.DomainProto.domain.getDefaultInstance();
      }

      @java.lang.Override
      public org.eagle.DomainProto.domain build() {
        org.eagle.DomainProto.domain result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.eagle.DomainProto.domain buildPartial() {
        org.eagle.DomainProto.domain result = new org.eagle.DomainProto.domain(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.eagle.DomainProto.domain result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.domainName_ = domainName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.interval_ = interval_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eagle.DomainProto.domain) {
          return mergeFrom((org.eagle.DomainProto.domain)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eagle.DomainProto.domain other) {
        if (other == org.eagle.DomainProto.domain.getDefaultInstance()) return this;
        if (!other.getDomainName().isEmpty()) {
          domainName_ = other.domainName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getInterval() != 0L) {
          setInterval(other.getInterval());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                domainName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                interval_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object domainName_ = "";
      /**
       * <code>string domain_name = 1;</code>
       * @return The domainName.
       */
      public java.lang.String getDomainName() {
        java.lang.Object ref = domainName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domainName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string domain_name = 1;</code>
       * @return The bytes for domainName.
       */
      public com.google.protobuf.ByteString
          getDomainNameBytes() {
        java.lang.Object ref = domainName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domainName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string domain_name = 1;</code>
       * @param value The domainName to set.
       * @return This builder for chaining.
       */
      public Builder setDomainName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        domainName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string domain_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDomainName() {
        domainName_ = getDefaultInstance().getDomainName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string domain_name = 1;</code>
       * @param value The bytes for domainName to set.
       * @return This builder for chaining.
       */
      public Builder setDomainNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        domainName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.protobuf.Type type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.protobuf.Type type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.Type type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public org.eagle.DomainProto.Type getType() {
        org.eagle.DomainProto.Type result = org.eagle.DomainProto.Type.forNumber(type_);
        return result == null ? org.eagle.DomainProto.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.protobuf.Type type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(org.eagle.DomainProto.Type value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.Type type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private long interval_ ;
      /**
       * <code>int64 interval = 3;</code>
       * @return The interval.
       */
      @java.lang.Override
      public long getInterval() {
        return interval_;
      }
      /**
       * <code>int64 interval = 3;</code>
       * @param value The interval to set.
       * @return This builder for chaining.
       */
      public Builder setInterval(long value) {

        interval_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 interval = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterval() {
        bitField0_ = (bitField0_ & ~0x00000004);
        interval_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.domain)
    }

    // @@protoc_insertion_point(class_scope:protobuf.domain)
    private static final org.eagle.DomainProto.domain DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.eagle.DomainProto.domain();
    }

    public static org.eagle.DomainProto.domain getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<domain>
        PARSER = new com.google.protobuf.AbstractParser<domain>() {
      @java.lang.Override
      public domain parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<domain> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<domain> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.eagle.DomainProto.domain getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface quality_configOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.quality_config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protobuf.domain configs = 1;</code>
     */
    java.util.List<org.eagle.DomainProto.domain> 
        getConfigsList();
    /**
     * <code>repeated .protobuf.domain configs = 1;</code>
     */
    org.eagle.DomainProto.domain getConfigs(int index);
    /**
     * <code>repeated .protobuf.domain configs = 1;</code>
     */
    int getConfigsCount();
    /**
     * <code>repeated .protobuf.domain configs = 1;</code>
     */
    java.util.List<? extends org.eagle.DomainProto.domainOrBuilder> 
        getConfigsOrBuilderList();
    /**
     * <code>repeated .protobuf.domain configs = 1;</code>
     */
    org.eagle.DomainProto.domainOrBuilder getConfigsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.quality_config}
   */
  public static final class quality_config extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.quality_config)
      quality_configOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        quality_config.class.getName());
    }
    // Use quality_config.newBuilder() to construct.
    private quality_config(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private quality_config() {
      configs_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eagle.DomainProto.internal_static_protobuf_quality_config_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eagle.DomainProto.internal_static_protobuf_quality_config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eagle.DomainProto.quality_config.class, org.eagle.DomainProto.quality_config.Builder.class);
    }

    public static final int CONFIGS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.eagle.DomainProto.domain> configs_;
    /**
     * <code>repeated .protobuf.domain configs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.eagle.DomainProto.domain> getConfigsList() {
      return configs_;
    }
    /**
     * <code>repeated .protobuf.domain configs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.eagle.DomainProto.domainOrBuilder> 
        getConfigsOrBuilderList() {
      return configs_;
    }
    /**
     * <code>repeated .protobuf.domain configs = 1;</code>
     */
    @java.lang.Override
    public int getConfigsCount() {
      return configs_.size();
    }
    /**
     * <code>repeated .protobuf.domain configs = 1;</code>
     */
    @java.lang.Override
    public org.eagle.DomainProto.domain getConfigs(int index) {
      return configs_.get(index);
    }
    /**
     * <code>repeated .protobuf.domain configs = 1;</code>
     */
    @java.lang.Override
    public org.eagle.DomainProto.domainOrBuilder getConfigsOrBuilder(
        int index) {
      return configs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < configs_.size(); i++) {
        output.writeMessage(1, configs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < configs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, configs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.eagle.DomainProto.quality_config)) {
        return super.equals(obj);
      }
      org.eagle.DomainProto.quality_config other = (org.eagle.DomainProto.quality_config) obj;

      if (!getConfigsList()
          .equals(other.getConfigsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getConfigsCount() > 0) {
        hash = (37 * hash) + CONFIGS_FIELD_NUMBER;
        hash = (53 * hash) + getConfigsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.eagle.DomainProto.quality_config parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eagle.DomainProto.quality_config parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eagle.DomainProto.quality_config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eagle.DomainProto.quality_config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eagle.DomainProto.quality_config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eagle.DomainProto.quality_config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eagle.DomainProto.quality_config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.eagle.DomainProto.quality_config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.eagle.DomainProto.quality_config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.eagle.DomainProto.quality_config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.eagle.DomainProto.quality_config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.eagle.DomainProto.quality_config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.eagle.DomainProto.quality_config prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.quality_config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.quality_config)
        org.eagle.DomainProto.quality_configOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eagle.DomainProto.internal_static_protobuf_quality_config_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eagle.DomainProto.internal_static_protobuf_quality_config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eagle.DomainProto.quality_config.class, org.eagle.DomainProto.quality_config.Builder.class);
      }

      // Construct using org.eagle.DomainProto.quality_config.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (configsBuilder_ == null) {
          configs_ = java.util.Collections.emptyList();
        } else {
          configs_ = null;
          configsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eagle.DomainProto.internal_static_protobuf_quality_config_descriptor;
      }

      @java.lang.Override
      public org.eagle.DomainProto.quality_config getDefaultInstanceForType() {
        return org.eagle.DomainProto.quality_config.getDefaultInstance();
      }

      @java.lang.Override
      public org.eagle.DomainProto.quality_config build() {
        org.eagle.DomainProto.quality_config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.eagle.DomainProto.quality_config buildPartial() {
        org.eagle.DomainProto.quality_config result = new org.eagle.DomainProto.quality_config(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.eagle.DomainProto.quality_config result) {
        if (configsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            configs_ = java.util.Collections.unmodifiableList(configs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.configs_ = configs_;
        } else {
          result.configs_ = configsBuilder_.build();
        }
      }

      private void buildPartial0(org.eagle.DomainProto.quality_config result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eagle.DomainProto.quality_config) {
          return mergeFrom((org.eagle.DomainProto.quality_config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eagle.DomainProto.quality_config other) {
        if (other == org.eagle.DomainProto.quality_config.getDefaultInstance()) return this;
        if (configsBuilder_ == null) {
          if (!other.configs_.isEmpty()) {
            if (configs_.isEmpty()) {
              configs_ = other.configs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureConfigsIsMutable();
              configs_.addAll(other.configs_);
            }
            onChanged();
          }
        } else {
          if (!other.configs_.isEmpty()) {
            if (configsBuilder_.isEmpty()) {
              configsBuilder_.dispose();
              configsBuilder_ = null;
              configs_ = other.configs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              configsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetConfigsFieldBuilder() : null;
            } else {
              configsBuilder_.addAllMessages(other.configs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.eagle.DomainProto.domain m =
                    input.readMessage(
                        org.eagle.DomainProto.domain.parser(),
                        extensionRegistry);
                if (configsBuilder_ == null) {
                  ensureConfigsIsMutable();
                  configs_.add(m);
                } else {
                  configsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.eagle.DomainProto.domain> configs_ =
        java.util.Collections.emptyList();
      private void ensureConfigsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          configs_ = new java.util.ArrayList<org.eagle.DomainProto.domain>(configs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.eagle.DomainProto.domain, org.eagle.DomainProto.domain.Builder, org.eagle.DomainProto.domainOrBuilder> configsBuilder_;

      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public java.util.List<org.eagle.DomainProto.domain> getConfigsList() {
        if (configsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(configs_);
        } else {
          return configsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public int getConfigsCount() {
        if (configsBuilder_ == null) {
          return configs_.size();
        } else {
          return configsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public org.eagle.DomainProto.domain getConfigs(int index) {
        if (configsBuilder_ == null) {
          return configs_.get(index);
        } else {
          return configsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public Builder setConfigs(
          int index, org.eagle.DomainProto.domain value) {
        if (configsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigsIsMutable();
          configs_.set(index, value);
          onChanged();
        } else {
          configsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public Builder setConfigs(
          int index, org.eagle.DomainProto.domain.Builder builderForValue) {
        if (configsBuilder_ == null) {
          ensureConfigsIsMutable();
          configs_.set(index, builderForValue.build());
          onChanged();
        } else {
          configsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public Builder addConfigs(org.eagle.DomainProto.domain value) {
        if (configsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigsIsMutable();
          configs_.add(value);
          onChanged();
        } else {
          configsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public Builder addConfigs(
          int index, org.eagle.DomainProto.domain value) {
        if (configsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigsIsMutable();
          configs_.add(index, value);
          onChanged();
        } else {
          configsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public Builder addConfigs(
          org.eagle.DomainProto.domain.Builder builderForValue) {
        if (configsBuilder_ == null) {
          ensureConfigsIsMutable();
          configs_.add(builderForValue.build());
          onChanged();
        } else {
          configsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public Builder addConfigs(
          int index, org.eagle.DomainProto.domain.Builder builderForValue) {
        if (configsBuilder_ == null) {
          ensureConfigsIsMutable();
          configs_.add(index, builderForValue.build());
          onChanged();
        } else {
          configsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public Builder addAllConfigs(
          java.lang.Iterable<? extends org.eagle.DomainProto.domain> values) {
        if (configsBuilder_ == null) {
          ensureConfigsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, configs_);
          onChanged();
        } else {
          configsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public Builder clearConfigs() {
        if (configsBuilder_ == null) {
          configs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          configsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public Builder removeConfigs(int index) {
        if (configsBuilder_ == null) {
          ensureConfigsIsMutable();
          configs_.remove(index);
          onChanged();
        } else {
          configsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public org.eagle.DomainProto.domain.Builder getConfigsBuilder(
          int index) {
        return internalGetConfigsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public org.eagle.DomainProto.domainOrBuilder getConfigsOrBuilder(
          int index) {
        if (configsBuilder_ == null) {
          return configs_.get(index);  } else {
          return configsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public java.util.List<? extends org.eagle.DomainProto.domainOrBuilder> 
           getConfigsOrBuilderList() {
        if (configsBuilder_ != null) {
          return configsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(configs_);
        }
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public org.eagle.DomainProto.domain.Builder addConfigsBuilder() {
        return internalGetConfigsFieldBuilder().addBuilder(
            org.eagle.DomainProto.domain.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public org.eagle.DomainProto.domain.Builder addConfigsBuilder(
          int index) {
        return internalGetConfigsFieldBuilder().addBuilder(
            index, org.eagle.DomainProto.domain.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.domain configs = 1;</code>
       */
      public java.util.List<org.eagle.DomainProto.domain.Builder> 
           getConfigsBuilderList() {
        return internalGetConfigsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.eagle.DomainProto.domain, org.eagle.DomainProto.domain.Builder, org.eagle.DomainProto.domainOrBuilder> 
          internalGetConfigsFieldBuilder() {
        if (configsBuilder_ == null) {
          configsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.eagle.DomainProto.domain, org.eagle.DomainProto.domain.Builder, org.eagle.DomainProto.domainOrBuilder>(
                  configs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          configs_ = null;
        }
        return configsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.quality_config)
    }

    // @@protoc_insertion_point(class_scope:protobuf.quality_config)
    private static final org.eagle.DomainProto.quality_config DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.eagle.DomainProto.quality_config();
    }

    public static org.eagle.DomainProto.quality_config getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<quality_config>
        PARSER = new com.google.protobuf.AbstractParser<quality_config>() {
      @java.lang.Override
      public quality_config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<quality_config> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<quality_config> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.eagle.DomainProto.quality_config getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_domain_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_domain_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_quality_config_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_quality_config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)protobuf/src/main/resources/domains.pr" +
      "oto\022\010protobuf\032\037google/protobuf/timestamp" +
      ".proto\032\033google/protobuf/empty.proto\"M\n\006d" +
      "omain\022\023\n\013domain_name\030\001 \001(\t\022\034\n\004type\030\002 \001(\016" +
      "2\016.protobuf.Type\022\020\n\010interval\030\003 \001(\003\"3\n\016qu" +
      "ality_config\022!\n\007configs\030\001 \003(\0132\020.protobuf" +
      ".domain*\030\n\004Type\022\007\n\003QOS\020\000\022\007\n\003QOE\020\0012_\n\024Qua" +
      "lityConfigService\022G\n\023UpsertQualityConfig" +
      "\022\030.protobuf.quality_config\032\026.google.prot" +
      "obuf.EmptyB\030\n\torg.eagleB\013DomainProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_protobuf_domain_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_domain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_domain_descriptor,
        new java.lang.String[] { "DomainName", "Type", "Interval", });
    internal_static_protobuf_quality_config_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_quality_config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_quality_config_descriptor,
        new java.lang.String[] { "Configs", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
